version: "3.8"

services:
  nginx:
    image: nginx:1.25
    container_name: wordpress_nginx
    ports:
      - "8000:80"  # local development environment
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./config/wp-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=${WP_DOMAIN}
    depends_on:
      - wordpress
    networks:
      - frontend
      - backend

  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.3
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - conf.d:/etc/nginx/conf.d
    environment:
      - DEFAULT_HOST=${WP_DOMAIN}
    restart: always
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 60s
      timeout: 10s
      retries: 3

  wordpress:
    image: wordpress:6.4.2-php8.2-fpm
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini:ro
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASS}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WP_TABLE_PREFIX:-wp_}
      - VIRTUAL_HOST=${WP_DOMAIN}
    depends_on:
      - mysql
    restart: always
    networks:
      - frontend
      - backend
    mem_limit: 1g

  mysql:
    image: mariadb:10.11.5
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${WP_DB_NAME}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD=${WP_DB_PASS}
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    restart: always
    networks:
      - backend
    ports:
      - "3306:3306"  # local development environment
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${DB_ROOT_PASS}",
        ]
      interval: 20s
      timeout: 10s
      retries: 3
    mem_limit: 1g

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    ports:
      - "8080:80"  # local development environment
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=http://localhost:8080
      - VIRTUAL_HOST=${PMA_DOMAIN}
      - UPLOAD_LIMIT=100M
    depends_on:
      - mysql
    restart: always
    networks:
      - frontend
      - backend
    mem_limit: 512m

networks:
  frontend:
  backend:

volumes:
  wordpress_data:
  db_data:
  vhost.d:
  html:
  conf.d: 